apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boot-r
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
      - sourcerepositories
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - jenkins.io
    resources:
      - plugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jenkins.io
    resources:
      - users
    verbs:
      - create
      - update
      - get
      - list
      - watch
  - apiGroups:
      - jenkins.io
    resources:
      - releases
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
      - pipelinestructures
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - jenkins.io
    resources:
      - environments
    verbs:
      - create
      - list
      - get
      - patch
      - update
  - apiGroups:
      - jenkins.io
    resources:
      - extensions
    verbs:
      - get
      - list
  - apiGroups:
      - vault.banzaicloud.com
    resources:
      - vaults
    verbs:
      - get
      - list
      - watch
