{{- if (include "jxl-boot.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: jx-boot-secrets
  labels:
    {{- include "jxl-boot.labels" . | nindent 4 }}
type: Opaque
data:
  secrets.yaml: |-
    secrets:
      adminUser:
        password: {{ .Values.adminUser.username }}
        username: {{ .Values.adminUser.password }}
      hmacToken: {{ .Values.hmacToken }}
      pipelineUser:
        email: {{ .Values.pipelineUser.email }}
        token: {{ .Values.pipelineUser.token }}
        username: {{ .Values.pipelineUser.username }}
{{- end }}
